name: Bug report for fdh.store
description: File a bug report.
title: "[Bug]: "
labels: ["status: needs triaging", "bug"]
body:
  - type: markdown
    attributes:
      value: "## System information"
  - type: markdown
    attributes:
      value: |
        The system information will help us reproduce the issue in the same environment
  - type: input
    attributes:
      label: Operating system name and version
    validations:
      required: true
  - type: input
    attributes:
      label: Browser name
  - type: markdown
    attributes:
      value: "## Describe the issue"
  - type: markdown
    attributes:
      value: |
        Please explain your issue in-depth along with the relevant screenshots and code snippets
  - type: textarea
    attributes:
      label: What happended?
      placeholder: A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
    validations:
      required: true
